- block:
  - include_tasks: virtualenv.yml

  - assert:
      that:
        - "django_settings_pattern in ['localsettings', 'jsonsettings', 'none']"
      msg: "django_settings_pattern must be either 'localsettings', 'jsonsettings' or 'none'"

  - include_tasks: config_localsettings.yml
    when: "django_settings_pattern == 'localsettings'"

  - include_tasks: config_jsonsettings.yml
    when: "django_settings_pattern == 'jsonsettings'"

  - include_tasks: manage.yml

  - include_tasks: fix_static_media_permissions.yml


  become: "{{ ansible_user|default('root') != django_user }}"
  become_user: "{{ django_user }}"
